### PR TITLE
Quality of life improvements for Objectify v6

### PR DESCRIPTION
**Pull request by frew**
Sorry for the poor pull etiquette here in batching updates. Can separate into multiple pieces or pull things out if it would be helpful. This is from migrating Streak's codebase to v6 which we're currently deploying.

Changes:
1) Add and remove s~ when converting from legacy url safe (Cloud Datastore doesn't use s~ prefix, there are a couple places where we need the legacy url safe keys to match by string comparison).
2) Expose the TransactionHandle (needed for our Spanner dual-writing configuration).
3) Make HybridQueryResults.safePartition always partition at max 1000. Cloud Datastore fails the request if it asks for more than 1000 keys in one go, so I think this is the correct fix.
4) Make SerializeTranslatorFactory hold on to the first exception when deserializing before it tries to do it again with the alternate value for the zip annotation. This helps with debugging (e.g. lets you know whether the serialization UID didn't match).

### CODE REVIEW

**Comment by stickfigure** [comment]
Looks good - ready for a point release?

**Comment by frew** [comment]
Yeah - we're currently pulling in a snapshot release I cut to test it out, so getting back on an official release would be great!

**Comment by stickfigure** [comment]
roger 6.0.1 is out!

**Comment by frew** [comment]
Awesome. Thanks!

**Pull request merged**
