### PR TITLE
Added MemcacheServiceFactory for EntityMemcache

### PR DESCRIPTION
**Pull request by zhaoyan1117**
This PR addresses issue: https://github.com/objectify/objectify/issues/319

All unit tests passed.

### CODE REVIEW

**Comment by stickfigure** [comment]
Hi, thanks for the PR! Would you mind changing it so that it uses the factory interface that comes built-into GAE? Look at IMemcacheServiceFactory. It has a funny name because google added the interfaces in retroactively, but we might as well use it.

**Comment by zhaoyan1117** [comment]
right on, and done! @stickfigure thx!

**Comment by stickfigure** [comment]
Thanks!

**Comment by zhaoyan1117** [comment]
Np @stickfigure , do you know when this change will be released to maven? thx!

**Comment by stickfigure** [comment]
v5.1.15 is on its way to maven right now. Cheers!

**Comment by zhaoyan1117** [comment]
thanks you sir!

**Pull request merged**
