### PR TITLE
Avoid reiterating the entities when saving

### PR DESCRIPTION
**Pull request by gabor-farkas**
(see the description of the case in the javadoc of the test)

### CODE REVIEW

**Comment by nbali** [comment]
@gabor-farkas afaik 5.x is v5 branch, not v5.2

**Comment by nbali** [comment]
@stickfigure 'official' stand  pls

**Comment by stickfigure** [comment]
Yes, put this on the v5 branch. v5.2 was an experimental branch and I don't think the code ever got pushed up (or will it likely ever). I may just delete it.

I'll merge the PR as soon as it's on v5. Thanks!

**Comment by gabor-farkas** [comment]
Done. (sorry for the delay)

**Comment by stickfigure** [comment]
Sorry, not sure why I missed notice of this before. Merged.

**Pull request merged**
